export default [
  {
    id: 1,
    categoriesId: 2,
    colorId: [1, 6],
    title: 'Бесконтактный термометр',
    price: 1000,
    img: 'img/thermometer.jpg',
  },
  {
    id: 2,
    categoriesId: 4,
    colorId: [3, 7],
    title: 'Умная колонка «Капсула»',
    price: 3500,
    img: 'img/smart-speaker.jpg',
  },
  {
    id: 3,
    categoriesId: 5,
    colorId: [3, 7],
    title: 'Электросамокат',
    price: 7100,
    img: 'img/electro-scooter.jpg',
  },
  {
    id: 4,
    categoriesId: 4,
    colorId: [7],
    title: 'Универсальный радар-детектор',
    price: 10720,
    img: 'img/radar-detector.jpg',
  },
  {
    id: 5,
    categoriesId: 1,
    colorId: [6],
    title: 'Умное сиденье для унитаза',
    price: 5400,
    img: 'img/toilet-seat.jpg',
  },
  {
    id: 6,
    categoriesId: 1,
    colorId: [3, 7],
    title: 'Погружной блендер',
    price: 3800,
    img: 'img/blender.jpg',
  },
  {
    id: 7,
    categoriesId: 4,
    colorId: [5, 7],
    title: 'Экшн-камера GoPro',
    price: 29440,
    img: 'img/gopro.jpg',
  },
  {
    id: 8,
    categoriesId: 4,
    colorId: [1, 5, 7],
    title: 'Смарт-часы',
    price: 6500,
    img: 'img/smart-watch.jpg',
  },
  {
    id: 9,
    categoriesId: 3,
    colorId: [3, 4],
    title: 'Многофункциональный рюкзак',
    price: 4990,
    img: 'img/backpack.jpg',
  },
  {
    id: 10,
    categoriesId: 1,
    colorId: [1],
    title: '«Морской» проектор',
    price: 17000,
    img: 'img/projector.jpg',
  },
  {
    id: 11,
    categoriesId: 3,
    colorId: [4, 6],
    title: 'Магнитные шнурки',
    price: 700,
    img: 'img/laces.jpg',
  },
  {
    id: 12,
    categoriesId: 2,
    colorId: [6, 7],
    title: 'Электромассажер для шеи',
    price: 6100,
    img: 'img/massager.jpg',
  },
];
